### ISSUE TITLE
Shopware 6.4 installation does not load administration bundle . window.__sw__.assetPath missing

### ISSUE THREAD

**Issue by JoshuaBehrens** [richardhaeser-com/sw-tweakwise#29]
**Describe the bug**

When you install the plugin in a Shopware 6.4 you do not see the administration changes like feed configuration and plugin configuration pages.

**To Reproduce**

1. Go to authenticated Shopware 6.4 administration
2. Upload, install and activate plugin
3. Follow instructions in DOC.md
4. Search for the "Tweakwise Feed" configuration
5. ![Grandma finds the internet](https://imgflip.com/s/meme/Grandma-Finds-The-Internet.jpg)
6. Doubt it is installed
7. See browser console
```
Uncaught TypeError: window.__sw__ is undefined
    <anonymous> https://…/bundles/rhaetweakwise/administration/js/rhae-tweakwise.js?170808411750699:2
    <anonymous> https://…/bundles/rhaetweakwise/administration/js/rhae-tweakwise.js?170808411750699:2
```

**Expected behavior**

I can follow the instructions in DOC.md when I install the plugin in a Shopware version, that is mentioned as supported in the composer.json.

**Desktop:**

 - OS: MacOS
 - Browser: Firefox
 - Version 122

**Additional context**

* Shopware version used 6.4.20.0
* Plugin version 2.4.4
* window.__sw__ has been introduced in Shopware 6.5 see https://github.com/shopware/shopware/commit/7144466a2b0763d5f6e13cb077051b871a5c7197#diff-5170ec7d0a50f984d7890e3d568dc80bf9e79d571d85ad16321fd7a87e4d44b4R24-R27 This lets me assume, that the administration javascript has built with Shopware 6.5 and therefore cannot work with 6.4

**Comment by haassie** [comment]
You can now use v2.5.0 which should fix this problem

**Comment by JoshuaBehrens** [comment]
I will have a look :)
