### ISSUE TITLE
Not all categories are loaded into Tweakwise

### ISSUE THREAD

**Issue by ROBBshopp** [richardhaeser-com/sw-tweakwise#31]
Niet alle categorieën worden gesynchroniseerd naar de Tweakwise backend lijkt het. Zie hieronder de verschillen tussen Shopware en Tweakwise qua categorieboom en categorieën die aan een product gekoppeld zijn. De versie van de plugin die we gebruiken is 
Tweakwise for Shopware Version: 2.4.2
Shopware 6.4.16.1

Als ik een (sub)categorie aan een van de mapjes toe voeg die wèl al in Tweakwise staan dan wordt die categorie wel binnengehaald. 

![image (8)](https://github.com/richardhaeser-com/sw-tweakwise/assets/148754129/9b3f8032-f287-4aff-b2de-b87fb1644c22)
![image (7)](https://github.com/richardhaeser-com/sw-tweakwise/assets/148754129/73a48d04-2dd8-45b6-a579-39b9d5c83bfe)
![image (6)](https://github.com/richardhaeser-com/sw-tweakwise/assets/148754129/e3656353-bd3e-40da-a870-e1d34793fe87)
![image (5)](https://github.com/richardhaeser-com/sw-tweakwise/assets/148754129/ffea90eb-39f7-45fd-8241-016051106f8d)

**Comment by haassie** [comment]
Staat deze categorie toevallig uit voor het tonen in het menu? Alleen categorieen die in het menu naar voren komen worden momenteel gesynchroniseerd. Dit is gekomen doordat er bij verschillende installaties veel categorieen naar Tweakwise gingen die vervuilend werkte in Tweakwise omdat terwijl ze helemaal niet gebruikt werden. Maar misschien is het goed om het optioneel te maken dat alleen categorieen die zichtbaar zijn in het menu gesynchroniseerd worden.

**Comment by ROBBshopp** [comment]
Hi Richard,

Bedankt voor je reactie. Veel van deze categorieën staan inderdaad op hide in
navigation omdat ze vooral voor SEO doeleinden gemaakt worden en niet allemaal
en de navigatiestructuur op de frontend zicht baar hoeven te zijn. Dus dat
optioneel maken lijkt me inderdaad een goede optie. Wij willen namelijk niet
alle categorieën in het menu van de website zichtbaar hebben maar deze pagina's
bevatten wel listers die gevuld moeten worden door Tweakwise en sommige
producten worden nu ook niet in search getoond omdat die aan die categorieën
hangen maar Tweakwise ze niet ziet en daardoor dus niet toont. Dit is
uiteindelijk wel te omzeilen met een afgeleide eigenschap die altijd een
standaard categorie vult maar dat maakt het weer complexer en minder
overzichtelijk.

Met vriendelijke groet,

Youp van den Berg

Instagram
[https://p33.p1.n0.cdn.getcloudapp.com/items/KoulnJgl/a7d19d25-e7fd-49a8-b0e4-6ba59690c76c.jpg?v=01bdb94a26c4283b9f2e20169bff6b3e]
[https://www.instagram.com/robbshopnl/] Facebook
[https://p33.p1.n0.cdn.getcloudapp.com/items/6quxNvmk/4d870a12-c6e9-4010-9b03-2da445c391af.png?v=39d0c11f25b9c1a06ee5670784b63221]
[https://www.facebook.com/ROBBshop.nl/] YouTube
[https://p33.p1.n0.cdn.getcloudapp.com/items/YEuQDO7j/b420922c-2f2c-4875-ae02-b067db1d7a58.png?v=4e4149c3acec38d5cb3e5f563202e661]
[https://www.youtube.com/user/ROBBshop] TrustPilot
[https://p33.p1.n0.cdn.getcloudapp.com/items/ApuGeEBy/87376d9a-5f33-4cee-9f0f-ed7e3c8a7fa6.png?v=a1eea3e3cd22cd40428132ba62d5610b]
[https://nl.trustpilot.com/review/robbshop.nl]

Email
[https://p33.p1.n0.cdn.getcloudapp.com/items/YEuQDOLE/80d4d910-5a3f-4a34-aa79-b85f847a9fa9.jpg?v=cfb0f1b6970aa10d9fd3312984d6eb15]
***@***.*** ***@***.*** ***@***.***
Website
[https://p33.p1.n0.cdn.getcloudapp.com/items/BluQRxkq/930fed8c-1e36-4c74-86b0-259ed4327df9.png?v=1482ef8f249cf0139161e46ac940af2e]
[https://robbshop.nl] www.ROBBshop.nl [https://robbshop.nl]
Telefoon
[https://p33.p1.n0.cdn.getcloudapp.com/items/wbuKvb25/66488b80-3b5f-4339-89e7-fc01a7c9b82e.png?v=9bc0c6b83e51e192a4991d524341c90a]
[tel:+31737620762] 073 762 0762 [tel:+31737620762]
Adres [https://p33.p1.n0.cdn.getcloudapp.com/items/9Zu0zQbx/da49f215-7134-4469-b713-69c4c1669537.jpg?v=c695b181d6b425ac855b084d1013e5c0] Gasstraat Oost 14B, 5349 AV, Oss

Logo [https://p33.p1.n0.cdn.getcloudapp.com/items/P8umNGLY/24f59519-b0e9-4556-a9c8-66041b233151.png?v=9f429c4716df0ee333b648aedd55ee9a]



Op 12 mrt. 2024 om 09:20 heeft richardhaeser-com/sw-tweakwise
***@***.***> het volgende
geschreven:

Staat deze categorie toevallig uit voor het tonen in het menu? Alleen
categorieen die in het menu naar voren komen worden momenteel gesynchroniseerd.
Dit is gekomen doordat er bij verschillende installaties veel categorieen naar
Tweakwise gingen die vervuilend werkte in Tweakwise omdat terwijl ze helemaal
niet gebruikt werden. Maar misschien is het goed om het optioneel te maken dat
alleen categorieen die zichtbaar zijn in het menu gesynchroniseerd worden.

—
Reply to this email directly, view it on GitHub
[https://github.com/richardhaeser-com/sw-tweakwise/issues/31#issuecomment-1991130765] , or unsubscribe
