### ISSUE TITLE
Categories based on dynamic product groups are not allocated to products

### ISSUE THREAD

**Issue by Youpvdberg** [richardhaeser-com/sw-tweakwise#37]
Categories filled with products based on a dynamic product groups are not allocated as category to the product which causes the listers to be empty

**Comment by haassie** [comment]
Hi Youp, dynamic products groups are not supported. In a future version, we will make this work with Tweakwise filter options.

**Comment by Youpvdberg** [comment]
That would mean that the plugin is not usable for tweakwise listers at this time but only for search?

**Comment by Youpvdberg** [comment]
Dynamic product groups eliminate the need of constantly manually adding products to product groups which makes filling categories far more intuitive. For instance filling brand pages, 2nd chance products or specific product types based on attributes. I think the plugin should support both whereas the previous app did support dynamic product groups and a simple tool like channable also allocates the dynamic product groups to the products. When looking at a fully functional plugin for Shopware, all general aspects should be included IMHO.

**Comment by haassie** [comment]
@Youpvdberg we did try something. Are you able to test the branch task/streams of the package? `composer require richardhaeser/sw-tweakwise:dev-task/streams`. Would love if this resolves the issue with the dynamic product groups.

**Comment by robbertdesmit** [comment]
i merged it with 2.6.1

but now we get a error 
 [ErrorException]                                                 
  Warning: Undefined array key "c7d2dfb95437474e959c032444954677"  
Exception trace:
  at /XXXXX/FeedService.php:383
 RH\Tweakwise\Service\FeedService->renderProducts() at /XXXXX/FeedService.php:212
                                 

can you make sure the array key is only set when its set the way now is not good. tnx

**Comment by haassie** [comment]
Sorry, not all changes were committed in the last commit. Now you should not get any warning anymore.

**Comment by ReneProjectmonk** [comment]
oh wow @haassie , this would be amazing if this will work. We are working with so many dynamic product groups (based on stock, tags, release date etc) Now we show those groups in another theme style then with the Tweakwise theme. It would be really nice if we have this new feature up and running. We will send you a cake when its finished :)

**Comment by robbertdesmit** [comment]
@haassie  we are almost there with the import of the dynamic product groups but.
There are products that are also manual assigend to a categoty before they are assigned to a dynamic product group
we get  mi;tiple errors; can you maby make a in array fix or something for this ? 

We found some invalid products. Some products contain a duplicate category.
Please correct the following products:
 - 9a506f2fa91a435b85a79642065c4120 categoryId: 84ab34ea2ad261fffdab74e59c5fc950

**Comment by ROBvanROBBshop** [comment]
Any news?

**Comment by haassie** [comment]
I pushed an update that will check if a category is already added to the product. Can you try again? If this is not working, can you ask your customer succes manager of Tweakwise to give me access to the test environment where you are currently load this feed? That way I can see some more error messages.

**Comment by haassie** [comment]
For my own webshop, it is working fine at the moment. Important though is that your indexes should be up to date. If you are missing products, please update the indexes through the admin or via CLI.

**Comment by haassie** [comment]
This feature is now merged and will be released later today

**Comment by haassie** [comment]
@ReneProjectmonk You can install the latest version of the extension. You can update it on your testing environment for example. After the installation, please regenerate the feed. After that, products should also get linked to categories if a category is based on a dynamic product group. Please make sure the index is up to date (most often this is the case). If needed you can update the index in the SW admin or via CLI.

**Comment by ROBvanROBBshop** [comment]
Hi Richard, we use dynamic product groups for this product category. There is only 1 product at the moment. In shopware backend there is a dynamic product group with more products. (The products themselves might have categories selected at product level). Any thoughts why there is only 1 product visible? We have 2.7.0 installed by Dutch Drops.  

https://www.robbshop.nl/slimme-verlichting/philips-hue/philips-hue-e14
<img width="1323" alt="Screenshot 2024-04-04 at 10 51 50" src="https://github.com/richardhaeser-com/sw-tweakwise/assets/121808625/1e2de485-43ca-429a-abd7-2153d2213442">
<img width="1330" alt="Screenshot 2024-04-04 at 10 51 44" src="https://github.com/richardhaeser-com/sw-tweakwise/assets/121808625/ef521fce-a8b2-4925-8fed-96b99abfb541">

**Comment by haassie** [comment]
Hi, my first reaction would be: are the indexes up to date? I've seen such behaviour before when the indexes were not up to date. You can update those in the admin of Shopware (see https://github.com/richardhaeser-com/sw-tweakwise/blob/main/DOC.md#create-feed-config). If that is not the solution, it would be great if you can give me access to a test-environment where we can reproduce the issue. You can send the login credentials to Rudolf of Tweakwise if you can.

**Comment by ROBvanROBBshop** [comment]
We solved it by removing the manual products from the feed. It would be nice if the dynamic productfeed overwrites the manual selection (or combines it even) is that an option?
