### ISSUE TITLE
JS errors after plugin activation

### ISSUE THREAD

**Issue by klau85** [richardhaeser-com/sw-tweakwise#45]
Hi,
After i install and activate the plugin, if i go to storefront, on any page, there are a lot of errors in the console (see attachement)

![image](https://github.com/user-attachments/assets/2f42feac-cc41-4466-851d-069a7d7be282)

it looks like all other plugins don't get loaded anymore

OS Debian buster
php 8.2.21
shopware 6.6.1.0
Tweakwise plugin "richardhaeser/sw-tweakwise": "dev-main"

**Comment by haassie** [comment]
I will check it in another installation

**Comment by haassie** [comment]
An update is pushed to dev-main. Can you check if this fixes your problem?

**Comment by haassie** [comment]
Fixed
